# Generated by Django 5.0 on 2024-01-03 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("hispanic_latino", "Hispanic or Latino"),
                            (
                                "americanIndian_alaskaNative",
                                "American Indian or Alaska Native",
                            ),
                            ("asian", "Asian"),
                            ("black_africanAmerican", "Black or African American"),
                            ("hawaiian", "Native Hawaiian or Other Pacific Islander"),
                            ("two_or_more", "Two or More Races"),
                            ("white", "White"),
                            ("none", "Prefer not to specify"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "veteran_status",
                    models.CharField(
                        choices=[
                            ("no", "I am not a protected veteran"),
                            (
                                "yes",
                                "I identify as one or more of the classifications of protected veteran listed above",
                            ),
                            ("none", "Prefer not to specify"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "disability_status",
                    models.CharField(
                        choices=[
                            (
                                "yes",
                                "Yes, I have a disability, or have had one in the past",
                            ),
                            (
                                "no",
                                "No, I do not have a disability and have not had one in the past",
                            ),
                            ("none", "Prefer not to answer"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("notice_period", models.CharField(default="", max_length=50)),
                (
                    "desired_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "desired_salary_currency",
                    models.CharField(
                        choices=[
                            ("usd", "USD"),
                            ("eur", "EUR"),
                            ("gbp", "GBP"),
                            ("inr", "INR"),
                            ("none", "Prefer not to specify"),
                        ],
                        default="none",
                        max_length=4,
                    ),
                ),
                ("work_authorization_status", models.BooleanField(default=True)),
                ("visa_sponsorship_status", models.BooleanField(default=False)),
                (
                    "work_preference",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                        ],
                        default="onsite",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
