# Generated by Django 5.0 on 2024-01-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_education_personalinfo_skill_workexperience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
