# Generated by Django 5.0 on 2024-01-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="chat_model",
            field=models.FileField(null=True, upload_to="cht_mdl/"),
        ),
    ]
