# Generated by Django 5.0 on 2024-01-08 10:30

import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_alter_coverletter_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverletter",
            name="chat_model",
            field=models.FileField(
                null=True, upload_to=resumes.models.PathAndRename("cht_mdl")
            ),
        ),
        migrations.AlterField(
            model_name="coverletter",
            name="file",
            field=models.FileField(
                upload_to=resumes.models.PathAndRename("coverletters")
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="chat_model",
            field=models.FileField(
                null=True, upload_to=resumes.models.PathAndRename("cht_mdl")
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(upload_to=resumes.models.PathAndRename("resumes")),
        ),
    ]
