# Generated by Django 5.0 on 2024-01-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resumes",
            "0005_alter_coverletter_chat_model_alter_coverletter_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coverletter",
            name="filename",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="filename",
            field=models.TextField(blank=True),
        ),
    ]
