# Generated by Django 5.0 on 2024-06-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robos', '0002_remove_jobtype_type_jobtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
