# Generated by Django 5.0 on 2024-01-15 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resumes", "0007_onboardingdetails"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_keyword", models.CharField(blank=True, max_length=255)),
                ("campaign_type", models.CharField(blank=True, max_length=255)),
                ("job_board", models.CharField(blank=True, max_length=255)),
                ("jobs_applied", models.IntegerField(blank=True, default=0)),
                ("country_selected", models.CharField(blank=True, max_length=255)),
                ("job_type", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "resume",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resumes.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrapedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_source", models.CharField(blank=True, max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("posted_contact", models.CharField(blank=True, max_length=255)),
                ("apply_type", models.CharField(blank=True, max_length=255)),
                ("job_url", models.URLField(blank=True)),
                ("job_location", models.CharField(blank=True, max_length=255)),
                ("job_location_city", models.CharField(blank=True, max_length=255)),
                ("job_location_state", models.CharField(blank=True, max_length=255)),
                ("job_location_country", models.CharField(blank=True, max_length=255)),
                ("job_location_zip", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("job_type", models.CharField(blank=True, max_length=255)),
                ("work_type", models.CharField(blank=True, max_length=255)),
                ("job_description", models.TextField(blank=True)),
                ("is_visa_required", models.BooleanField(blank=True, default=False)),
                ("date_posted", models.DateField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_jobs",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
    ]
