# Generated by Django 5.0 on 2024-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
